server:
  address: "localhost"
  port: 8080

database:
  user: "postgres"
  dbname: "cyber_garden"
  host: "localhost"
  port: 5432
  sslmode: "disable"
  init_db:
    path_to_dir: "migrations/plant-database/json_rus"
    init: true

translate_mode: false

logger_level: "debug"

recognize_api:
  max_images: 5
  base_url: "https://my-api.plantnet.org/v2/identify/"
  count_results: 5
  image_field: "images"

trefle_api:
  base_url: "https://trefle.io/api/v1/plants/"
  count_plants: 20

perenual_api:
  base_url: "https://www.perenual.com/api"

cookie_settings:
  secure: "true"
  http_only: "true"
  expire_date:
    years: 0
    months: 0
    days: 7
