version: "3.3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - server

  postgres:
    hostname: postgres
    container_name: postgresql
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cyber_garden"]
      interval: 2s
      timeout: 1s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cyber_garden
      POSTGRES_PASSWORD: admin
    networks:
      - server

networks:
  server:
    driver: bridge
