version: "3.3"
services:
  backend:
    hostname: app
    container_name: cyberbed-image
    image: milchenko/cyberbed-image
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ~/plant-database:/root/plant-database
    networks:
      - server

  postgres:
    hostname: postgres
    container_name: postgresql
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cyber_garden"]
      interval: 2s
      timeout: 2s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cyber_garden
      POSTGRES_PASSWORD: admin
      DATABASE_HOST: postgres
    networks:
      - server

networks:
  server:
    driver: bridge
    name: "server"
    external: false
