name: deploy
on:
  [push]
  # push:
  #   branches:
  #     - "main"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: copy files via ssh secrets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yaml, configs/app/deploy.yaml"
          target: "backend"
          rm: true
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          IS_INIT_DB: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker rm -f $(docker ps -aq)
            docker rmi -f $(docker images -aq)

            export RECOGNIZE_API_TOKEN=${{ secrets.RECOGNIZE_API_TOKEN }}
            export TREFLE_API_TOKEN=${{ secrets.TREFLE_API_TOKEN }}
            export PERENUAL_API_TOKEN=${{ secrets.PERENUAL_API_TOKEN }}
            echo 'RECOGNIZE_API_TOKEN=$RECOGNIZE_API_TOKEN\nTREFLE_API_TOKEN=$TREFLE_API_TOKEN\nPERENUAL_API_TOKEN=$PERENUAL_API_TOKEN' > ~/backend/.env.prod

            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cyberbed-image
            cd ~/backend 
            docker compose up -d
